services:
  qwen3vl:
    image: qwen3vl:latest
    container_name: qwen3vl
    gpus: all
    ipc: host
    volumes:
      - /home/ct/qwen3-vl:/workspace
    expose:
      - "2333"
    ports:
      - "2333:2333"
    networks:
      - qwen-net
    restart: unless-stopped
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cftunnel
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    networks:
      - qwen-net

networks:
  qwen-net:
    driver: bridge
