services:
  qwen3vl:
    image: qwenllm/qwenvl:qwen3vl-cu128
    container_name: qwen3vl
    gpus: all
    ipc: host
    volumes:
      - ./start_vllm.sh:/start_vllm.sh:ro
      - /home/ct/.cache/huggingface/hub:/root/.cache/huggingface/hub \
    command: ["bash", "/start_vllm.sh"]
    ports:
      - "2333:2333"
    networks:
      - qwen-net
    restart: unless-stopped
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cftunnel
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    networks:
      - qwen-net

networks:
  qwen-net:
    driver: bridge
